In [16]:
import pandas as pd

list_sensors=['Sensor1_x','Sensor1_y','Sensor1_z','Sensor2_x','Sensor2_y','Sensor2_z', 'Sensor3_x','Sensor3_y','Sensor3_z']
def tabulate_data(file):
    f = open(filename,'rt')
    file_as_list= [[token.split(',') for token in line.split(';')] for line in f.readlines()]
    data=pd.DataFrame(file_as_list).T
    data=data[0].apply(pd.Series)
    headers=['Trackers']
    headers.extend(list_sensors*10)
    data.columns=headers
    return data.head()

filename='./recordings+7.14+Luc/hooks_waterbag_hard_40-T7L-1531552258694.txt'
tabulate_data(filename)

,Trackers,Sensor1_x,Sensor1_y,Sensor1_z,Sensor2_x,Sensor2_y,Sensor2_z,Sensor3_x,Sensor3_y,Sensor3_z,...,Sensor3_z,Sensor1_x,Sensor1_y,Sensor1_z,Sensor2_x,Sensor2_y,Sensor2_z,Sensor3_x,Sensor3_y,Sensor3_z
0,T7L,-62,-283,47,-1852,-336,820,-585,367,482,...,460,118,270,140,-1838,-326,678,-583,368,467
1,T7L,140,215,130,-1870,-355,715,-587,365,471,...,478,53,-534,77,-1703,-647,787,-570,336,478
2,T7L,50,-550,90,-1754,-588,804,-575,342,480,...,488,188,-280,50,-1890,-393,870,-589,361,487
3,T7L,230,-340,60,-1890,-350,830,-589,365,483,...,531,-44,-1332,58,-1400,-120,1402,-540,388,540
4,T7L,-38,-1034,97,-1370,32,1354,-537,403,535,...,504,104,-98,46,-1658,-452,1044,-565,355,504